// <auto-generated />
using System;
using MicrosAccounting.Api.Brokers.StorageBrokers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MicrosAccounting.Api.Migrations
{
    [DbContext(typeof(StorageBroker))]
    [Migration("20240409184301_UserCategoryConfig")]
    partial class UserCategoryConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MicrosAccounting.Api.Models.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Accounting")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1a99ed58-54fc-4c2d-b68d-f0f8c96f88c8"),
                            Accounting = 0,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = new Guid("71577dac-0a17-4a58-8285-7fdc5c008b4e"),
                            Accounting = 0,
                            Name = "Other Income"
                        },
                        new
                        {
                            Id = new Guid("0ca6c0a4-2a85-4b88-9c42-2fb86334b1ed"),
                            Accounting = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = new Guid("ed29109f-27df-43f5-b40d-8b2d12da3738"),
                            Accounting = 1,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = new Guid("e1b10d79-d2e0-40bf-86d2-f7f05b868e66"),
                            Accounting = 1,
                            Name = "Mobile Connection"
                        },
                        new
                        {
                            Id = new Guid("ccabf5d2-4ad2-46c8-bd73-3d391f7ff918"),
                            Accounting = 1,
                            Name = "Internet"
                        },
                        new
                        {
                            Id = new Guid("ba0c060a-2c9d-441d-837c-40aaaebd30a3"),
                            Accounting = 1,
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("MicrosAccounting.Api.Models.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f45cc7a-75e5-43b3-9993-44a1a2f54c28"),
                            Amount = 6000m,
                            CategoryId = new Guid("1a99ed58-54fc-4c2d-b68d-f0f8c96f88c8"),
                            Comment = "some comment",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UserId = new Guid("47729a8b-e359-493e-a982-e7c818cd1220")
                        },
                        new
                        {
                            Id = new Guid("71065dfc-eaef-4f96-a1f9-5291a8467a86"),
                            Amount = 5000m,
                            CategoryId = new Guid("71577dac-0a17-4a58-8285-7fdc5c008b4e"),
                            Comment = "some comment",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UserId = new Guid("8121adf5-6db9-46bb-ae3b-60b547526438")
                        },
                        new
                        {
                            Id = new Guid("5714ede8-db42-4fa0-845c-47ff57d29ff1"),
                            Amount = 100m,
                            CategoryId = new Guid("ed29109f-27df-43f5-b40d-8b2d12da3738"),
                            Comment = "some comment",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UserId = new Guid("47729a8b-e359-493e-a982-e7c818cd1220")
                        },
                        new
                        {
                            Id = new Guid("72144c30-d401-4b4a-be4c-13dcf4a8e567"),
                            Amount = 500m,
                            CategoryId = new Guid("0ca6c0a4-2a85-4b88-9c42-2fb86334b1ed"),
                            Comment = "some comment",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UserId = new Guid("47729a8b-e359-493e-a982-e7c818cd1220")
                        },
                        new
                        {
                            Id = new Guid("070e7930-b979-43a2-b512-69ad2999c2c1"),
                            Amount = 90m,
                            CategoryId = new Guid("0ca6c0a4-2a85-4b88-9c42-2fb86334b1ed"),
                            Comment = "some comment",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UserId = new Guid("8121adf5-6db9-46bb-ae3b-60b547526438")
                        },
                        new
                        {
                            Id = new Guid("75b01b84-8590-4ce5-b2d6-b8fda47c2a4c"),
                            Amount = 101m,
                            CategoryId = new Guid("ed29109f-27df-43f5-b40d-8b2d12da3738"),
                            Comment = "some comment",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UserId = new Guid("47729a8b-e359-493e-a982-e7c818cd1220")
                        },
                        new
                        {
                            Id = new Guid("75c56079-9619-44a3-88a4-7675b09817d0"),
                            Amount = 40m,
                            CategoryId = new Guid("0ca6c0a4-2a85-4b88-9c42-2fb86334b1ed"),
                            Comment = "some comment",
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 0, 0, 0)),
                            UserId = new Guid("8121adf5-6db9-46bb-ae3b-60b547526438")
                        });
                });

            modelBuilder.Entity("MicrosAccounting.Api.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("47729a8b-e359-493e-a982-e7c818cd1220"),
                            Email = "adim@microsoft.com",
                            Password = "Hello!11"
                        },
                        new
                        {
                            Id = new Guid("8121adf5-6db9-46bb-ae3b-60b547526438"),
                            Email = "user@microsoft.com",
                            Password = "Hello!12"
                        });
                });

            modelBuilder.Entity("MicrosAccounting.Api.Models.Transactions.Transaction", b =>
                {
                    b.HasOne("MicrosAccounting.Api.Models.Categories.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicrosAccounting.Api.Models.Users.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MicrosAccounting.Api.Models.Categories.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MicrosAccounting.Api.Models.Users.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
